title: Joana Miranda
author: Joana Miranda
email: joana.miranda25@gmail.com
description: >
  Write an awesome description for your new site here. This could
  for example be used for SEO purposes.

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - .gitignore

date_format: "%b %-d, %Y"
